[build]
base = "/"
command = "pnpm run build:play"
publish = "./packages/drizzle-duckdb-wasm/playground/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
