[build]
base = "/"
command = "pnpm -F @proj-airi/drizzle-duckdb-wasm... run play:build"
publish = "./packages/drizzle-duckdb-wasm/playground/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
