packages:
  - packages/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'
catalog:
  '@antfu/eslint-config': ^4.13.0
  '@antfu/ni': ^24.3.0
  '@cspell/dict-ru_ru': ^2.3.0
  '@date-fns/tz': ^1.2.0
  '@duckdb/duckdb-wasm': 1.29.1-dev68.0
  '@iconify-json/solar': ^1.2.2
  '@types/d3': ^7.4.3
  '@types/d3-force': ^3.0.10
  '@types/node': ^22.15.17
  '@unocss/eslint-config': ^66.1.1
  '@unocss/eslint-plugin': ^66.1.1
  '@unocss/reset': ^66.1.1
  '@vitejs/plugin-vue': ^5.2.4
  '@vitest/browser': ^3.1.3
  '@vitest/coverage-v8': ^3.1.3
  '@vueuse/core': ^13.1.0
  apache-arrow: ^19.0.1
  bumpp: ^10.1.0
  changelogithub: ^13.13.0
  cross-env: ^7.0.3
  d3: ^7.9.0
  d3-force: ^3.0.0
  date-fns: ^4.1.0
  defu: ^6.1.4
  drizzle-kit: ^0.31.1
  es-toolkit: ^1.37.2
  eslint: ^9.26.0
  lint-staged: ^15.5.2
  playwright: ^1.52.0
  reka-ui: ^2.2.1
  rollup: ^4.40.2
  simple-git-hooks: ^2.13.0
  superjson: ^2.2.2
  taze: ^19.1.0
  typescript: ~5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.1
  unplugin-vue-router: ^0.12.0
  vite: ^6.3.5
  vite-plugin-inspect: ^11.0.1
  vitest: ^3.1.3
  vue: ^3.5.13
  vue-router: ^4.5.1
  vue-tsc: ^3.0.0-alpha.6
